repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    args: 
    - --manifest-path=2022/Cargo.toml
    - --
  - id: cargo-check
    args: 
    - --manifest-path=2022/Cargo.toml
    - --
  - id: clippy
    args: 
    - --manifest-path=2022/Cargo.toml
    - --
