[package]
name = "rust2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
itertools = "0.10.5"
lending-iterator = "0.1.6"
ringbuf = "0.3.1"
